/* Generated By:JJTree: Do not edit this line. Expression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.googlecode.brainfuck4j;

public
class Expression extends SimpleNode {
  public Expression(int id) {
    super(id);
  }

  public Expression(Brainfuck p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BrainfuckVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ae64492d71bd3bbee1843c987853b53e (do not edit this line) */
