/* Generated By:JJTree: Do not edit this line. Header.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.googlecode.brainfuck4j;

public
class Header extends SimpleNode {
  public Header(int id) {
    super(id);
  }

  public Header(Brainfuck p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BrainfuckVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ee0e87b8557e9a36ad059184a9c16bda (do not edit this line) */
