/* Generated By:JJTree: Do not edit this line. BlockExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.googlecode.brainfuck4j;

public
class BlockExpression extends SimpleNode {
  public BlockExpression(int id) {
    super(id);
  }

  public BlockExpression(Brainfuck p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BrainfuckVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=efb95d83a1e1c49198199a02c9cfb87a (do not edit this line) */
