/* Generated By:JJTree&JavaCC: Do not edit this line. BrainfuckConstants.java */
package com.googlecode.brainfuck4j;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BrainfuckConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INSTRUCTION_LITERAL = 7;
  /** RegularExpression Id. */
  int PROGRAM_NAME_KEYWORD = 8;
  /** RegularExpression Id. */
  int HEAP_SIZE_KEYWORD = 9;
  /** RegularExpression Id. */
  int CODE_KEYWORD = 10;
  /** RegularExpression Id. */
  int PROGRAM_NAME = 11;
  /** RegularExpression Id. */
  int HEAP_SIZE = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INSTRUCTION_LITERAL>",
    "\"Program\"",
    "\"Heapsize\"",
    "\"Code\"",
    "<PROGRAM_NAME>",
    "<HEAP_SIZE>",
    "\"[\"",
    "\"]\"",
  };

}
