/* Generated By:JavaCC: Do not edit this line. BrainfuckTreeConstants.java Version 4.2 */
package com.googlecode.brainfuck4j;

public interface BrainfuckTreeConstants
{
  public int JJTASTSTART = 0;
  public int JJTHEADER = 1;
  public int JJTPROGRAMHEADER = 2;
  public int JJTHEAPHEADER = 3;
  public int JJTEXPRESSION = 4;
  public int JJTUNARYEXPRESSION = 5;
  public int JJTBLOCKEXPRESSION = 6;


  public String[] jjtNodeName = {
    "ASTStart",
    "Header",
    "ProgramHeader",
    "HeapHeader",
    "Expression",
    "UnaryExpression",
    "BlockExpression",
  };
}
/* JavaCC - OriginalChecksum=53d9e81a1f0c1f8f932fc62ed315d0e6 (do not edit this line) */
